### ISSUE TITLE
zstd compression

### ISSUE THREAD

**Issue by cgb** [ashish01/hn-data-dumps#3]
Hey there,

Thanks for publishing your code on this - I've found it invaluable already in analysing stories and comments.

I've been experimenting with this code and can see the latest changes to zstd compress each row.  I've tested undoing those changes and using ZFS compression at the storage volume level.

Here are my results in case you were interested:

# row compression using zstd.compress in python:
```
$ du -sh hn2.db3 
12G     hn2.db3

$ du -sh hn2.db3 --apparent-size
12G     hn2.db3

$ sqlite3 hn2.db3 'SELECT * from hn_items ORDER BY id LIMIT 1'
1|(�/� �-

```

# ZFS
```
$ du -sh hn2-nozstd.db3
6.5G    hn2-nozstd.db3

$ du -sh hn2-nozstd.db3 --apparent-size
17G     hn2-nozstd.db3

$ sqlite3 hn2-nozstd.db3 'SELECT * from hn_items ORDER BY id LIMIT 1'
1|{"by":"pg","descendants":15,"id":1,"kids":[15,234509,487171,82729],"score":57,"time":1160418111,"title":"Y Combinator","type":"story","url":"http://ycombinator.com"}

```

I'm looking at testing SQLite extensions sqlite-zstd or sqlite_zstd_zfs to see if an in-database transparent encryption method might provide similar or better compression ratios without the need for an underlying filesystem with compression support.

Will report back any further results.

**Comment by ashish01** [comment]
I have changed the code to store data in parquet files instead of as SQLite DB. Parquet files can use ZSTD compression! Looks like ZSTD defaults whole hn dataset (~35M items) is around 5.4GB compressed. To read parquet files as SQL tables you can use duckdb

`select item_id, item_json from 'hn-*.parquet'`

<img width="492" alt="image" src="https://user-images.githubusercontent.com/151985/213846137-80723643-7772-415a-acd7-3dfd8ba9c612.png">
